image: node:lts-alpine

clone:
  depth: full # SonarCloud scanner needs the full history to assign issues properly

definitions:
  caches:
    sonar: ~/.sonar/cache # Caching SonarCloud artifacts will speed up your build
  steps:
    - step: &build-test-sonarcloud
        name: Build, test and analyze on SonarCloud
        caches:
          - node # See https://confluence.atlassian.com/bitbucket/caching-dependencies-895552876.html
          - sonar
        script:
          - npm install --force
          - npm test # Build your project and run
          - pipe: sonarsource/sonarcloud-scan:2.0.0
    - step: &check-quality-gate-sonarcloud
        name: Check the Quality Gate on SonarCloud
        script:
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6

pipelines:
  default:
    - parallel:
        - step:
            name: Build and Test
            caches:
              - node
            script:
              - npm install --force
              - npm test
        - step:
            name: Code linting
            script:
              - npm install --force
              - npx eslint -v
              - npx eslint .
            caches:
              - node
        - step: *build-test-sonarcloud
        - step: *check-quality-gate-sonarcloud
