image: node:lts-alpine

pipelines:
  default:
    #    - step:
    #        name: Code linting
    #        script:
    #          - npm install --force
    #          - npm run lint
    #        caches:
    #          - node
    - step:
        name: Testing
        caches:
          - node
        script:
          - npm install --force
          - npm run test:coverage
          - pipe: wget -qO - https://coverage.codacy.com/get.sh | sh -s -- report -r coverage/lcov.info
            variables:
              CODACY_PROJECT_TOKEN: $CODACY_PROJECT_TOKEN
        artifacts:
          - coverage/**
    - step:
        name: Security Scan
        script:
          # Run a security scan for sensitive data.
          # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
          - pipe: atlassian/git-secrets-scan:0.5.1
