name: Npm Publish Utils

on:
  push:
    branches:
      - master
    tags:
      - v*

permissions: read-all

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@main
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org"
      - run: npm install --force
      - run: npm test
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
          provenance: true
